wsgi/openshift/toShow/urls.py
from django.conf.urls import patterns, url
from toShow import views
from django.contrib.auth.decorators import login_required, user_passes_test

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^servicios/$', views.services, name='services'),
	url(r'^habitaciones/$', views.rooms, name='rooms'),
	url(r'^galeria/$', views.gallery, name='gallery'),
	url(r'^turismo/$', views.turism, name='tourism'),
	url(r'^contactenos/$', views.contact, name='contact'),	
)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'openshift.views.home', name='home'),
    # url(r'^openshift/', include('openshift.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('toShow.urls', namespace="toShow")), #here go /administration beside r'^'
)

wsgi/openshift/toShow/models.py
from django.db import models

class ImagesData (models.Model):	
	classs= models.CharField(max_length=50)
	dataId= models.CharField(max_length=50)
	dataType= models.CharField(max_length=50)
	href= models.CharField(max_length=200)
	src= models.CharField(max_length=100)
	alt= models.CharField(max_length=200)

	def __unicode__(self):  
		rpta = "classs: %s,dataId: %s, dataType: %s, href: %s,src: %s, alt: %s " % (self.classs, self.dataId, self.dataType,self.href, self.src, self.alt)
		return rpta

wsgi/openshift/toShow/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render, get_list_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from toShow.models import ImagesData

def index(request):	
	context = {'myPlace':'Inicio','menu':'index'} # addhering to the dictionery  (general)context new data, the place that i am
	return render(request,'index.html',context)	

def services(request):
	context = {'myPlace':'Servicios','menu':'services'}
	return render(request,'services.html',context)	

def rooms(request):
	context = {'myPlace':'Habitaciones','menu':'rooms'} 
	return render(request,'rooms.html',context)		

def gallery(request):
	allDataImages=ImagesData.objects.all()
	context = {'myPlace':'Galería','menu':'gallery','dataImages':allDataImages}  
	return render(request,'gallery.html',context)		

def turism(request):
	context = {'myPlace':'Turismo','menu':'tourism'} 
	return render(request,'tourism.html',context)		

def contact(request):
	context = {'myPlace':'Contacto','menu':'contact'} 
	return render(request,'contact.html',context)					

wsgi/openshift/views.py
import os
from django.shortcuts import render_to_response

def home(request):
    return render_to_response('home/home.html')

wsgi/openshift/templates/HostalRafael/Gallery-master/index.html
<!DOCTYPE HTML>
<!--
/*
 * blueimp Gallery Demo 2.10.0
 * https://github.com/blueimp/Gallery
 *
 * Copyright 2013, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
-->
<html lang="en">
<head>
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<meta charset="utf-8">
<title>blueimp Gallery</title>
<meta name="description" content="blueimp Gallery is a touch-enabled, responsive and customizable image and video gallery, carousel and lightbox, optimized for both mobile and desktop web browsers. It features swipe, mouse and keyboard navigation, transition effects, slideshow functionality, fullscreen support and on-demand content loading and can be extended to display additional content types.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="css/blueimp-gallery.css">
<link rel="stylesheet" href="css/blueimp-gallery-indicator.css">
<link rel="stylesheet" href="css/blueimp-gallery-video.css">
<link rel="stylesheet" href="css/demo.css">
</head>
<body>
<h1>blueimp Gallery</h1>
<p><a href="https://github.com/blueimp/Gallery">blueimp Gallery</a> is a touch-enabled, responsive and customizable image &amp; video gallery, carousel and lightbox, optimized for both mobile and desktop web browsers.<br>
It features swipe, mouse and keyboard navigation, transition effects, slideshow functionality, fullscreen support and on-demand content loading and can be extended to display additional content types.</p>
<ul class="navigation">
    <li><a href="https://github.com/blueimp/Gallery/tags">Download</a></li>
    <li><a href="https://github.com/blueimp/Gallery">Source Code</a></li>
    <li><a href="https://github.com/blueimp/Gallery/blob/master/README.md">Documentation</a></li>
    <li><a href="https://blueimp.net">&copy; Sebastian Tschan</a></li>
</ul>
<p><a href="https://github.com/blueimp/Gallery">blueimp Gallery</a> is based on <a href="http://swipejs.com/">Swipe</a>.</p>
<br>
<h2>Carousel image gallery</h2>
<!-- The Gallery as inline carousel, can be positioned anywhere on the page -->
<div id="blueimp-image-carousel" class="blueimp-gallery blueimp-gallery-carousel">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="play-pause"></a>
</div>
<br>
<h2>Carousel video gallery</h2>
<!-- The Gallery as inline carousel, can be positioned anywhere on the page -->
<div id="blueimp-video-carousel" class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="play-pause"></a>
</div>
<br>
<h2>Lightbox image gallery</h2>
<!-- The container for the list of example images -->
<div id="links" class="links"></div>
<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script src="js/blueimp-helper.js"></script>
<script src="js/blueimp-gallery.js"></script>
<script src="js/blueimp-gallery-fullscreen.js"></script>
<script src="js/blueimp-gallery-indicator.js"></script>
<script src="js/blueimp-gallery-video.js"></script>
<script src="js/blueimp-gallery-vimeo.js"></script>
<script src="js/blueimp-gallery-youtube.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
/*jslint evil: true */
/*global window, document*/
// Including jQuery via the protocol relative url above works for both http and https.
// Explicitly including jQuery via http allows running the Gallery demo as local file:
if (!window.jQuery) {
    document.write(
        '<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"><\/script>'
    );
}
</script>
<script src="js/jquery.blueimp-gallery.js"></script>
<script src="js/demo.js"></script>
</body> 
</html>

wsgi/openshift/templates/HostalRafael/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	
    <meta charset="utf-8" />
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
	

	<link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" type="text/css" />
	<link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.min.css" type="text/css" />
	<link rel="stylesheet" href="{{ STATIC_URL }}css/hotel.css" type="text/css" />
	<link rel="stylesheet" href="{{ STATIC_URL }}css/hotel-responsive.css" type="text/css" />
	<link rel="stylesheet" href="{{ STATIC_URL }}js/slider/default.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{ STATIC_URL }}css/nivo-slider.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{ STATIC_URL }}css/socialcount-with-icons.css" type="text/css" media="screen" />	

	<link rel="stylesheet" href="{{ STATIC_URL }}Gallery-master/css/blueimp-gallery.min.css">
	
	
	<style>
		div.ui-datepicker{
			font-size:11px;
		}
	</style>
		
    <!--[if lt IE 9]>
		<link rel="stylesheet" href="css/bootstrap_ie7.css" type="text/css">
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
       #map-canvas {
        height: 300px;
        width: 600px;
        margin: 0px;
        padding: 0px
      }
    </style>   

</head>	

<body>
	<!-- <div id="map-canvas"></div>	 -->
	<div class="container-fluid"> <!--(S)here es the main container froma pieces of web -->
		<!-- start header -->
		<div class="row">
			<div class="span4 logo">
				<a href="{% url 'toShow:index'  %}">
				<div class="row">
					<div class="span3 logo">
						<h1>Hospedaje<span>Rafael</span></h1>
						<!-- <p>&#9733;</p> -->
						<p><img src="{{ STATIC_URL }}css/images/signRafael.png" alt="" width="30" heigh="30" /></p>
					</div>
				</div>
				</a>
			</div>		
			<div class="span8  main_menu">
				<div class="navbar">
					<div class="container">
					 	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>

						<div class="nav-collapse span12" >
							<ul class="nav nav-pills"> <!-- this menu works woth petiocion in django -> exactly send tagMenu-->
								{% if menu == "index" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/">Inicio</a></li>

								{% if menu == "services" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/servicios">Servicios</a></li>

								{% if menu == "rooms" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/habitaciones">Habitaciones</a></li>

								{% if menu == "gallery" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/galeria">Galería</a></li>

								{% if menu == "tourism" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/turismo">Turismo</a></li>

								{% if menu == "contact" %}<li class="active">
								{% else %} <li class=""> {% endif %} <a href="/contactenos">Contactenos</a></li>
								
							</ul>
						</div><!-- /.nav-collapse -->
					</div>
				</div><!-- /navbar -->
			</div>
		</div>
		
		<div class="row offset10" >
			<ul data-facebook-action="recommend" data-url="#" class="socialcount socialcount-small recommend grade-a">
				<li class="facebook"><a target="_blank" title="Nuestro Facebook" href="https://www.facebook.com/hotelrafaelcamana"><span class="social-icon icon-facebook"></span><span class="count"></span></a></li>
				<li class="twitter"><a target="_blank" title="Nuestro Twitter" href="https://twitter.com/HospedajeRafael"><span class="social-icon icon-twitter"></span><span class="count"></span></a></li>
				<li class="googleplus"><a target="_blank" title="Nuestro Google Mas" href="https://plus.google.com/u/0/communities/100694529006737757231"><span class="social-icon icon-googleplus"></span><span class="count"></span></a></li>
			</ul>
		</div>
		<!-- end header -->
		
		{% block titleMenu %} {% endblock %}
		{% block slider %} {% endblock %}
		{% block places %} {% endblock %}
		{% block kindOfRooms %} {% endblock %}
		{% block photosGallery %} {% endblock %}
		{% block touristPlaces %} {% endblock %}
		{% block mapAndText %} {% endblock %}

		{% block structureFirst %} {% endblock %}

		{% block goodReferences %} {% endblock %}

	</div>	
	<!--(S)here es the main container froma pieces of web -->

	<footer>
		<div class="container">
		<div class="row footer_section_pre">

		<div class="span4">
			<h4>Hospedaje Rafael<span class="line"></span></h4>

			<p><span>Rafael I - </span>Avenida Quilca 255, Camaná, Arequipa</p>
			<p><span>Rafael II - </span>Avenida Quilca 330, Camaná, Arequipa</p>
			<p>Tel: +51-54-571000 <br />  <br />Email: hostalrafael@hostalrafael.com  </p>			
			
			<ul data-facebook-action="recommend" data-url="#" class="socialcount socialcount-small recommend grade-a">
				<li class="facebook"><a target="_blank" title="Nuestro Facebook" href="https://www.facebook.com/hotelrafaelcamana"><span class="social-icon icon-facebook"></span><span class="count"></span></a></li>
				<li class="twitter"><a target="_blank" title="Nuestro Twitter" href="https://twitter.com/HospedajeRafael"><span class="social-icon icon-twitter"></span><span class="count"></span></a></li>
				<li class="googleplus"><a target="_blank" title="Nuestro Google Mas" href="https://plus.google.com/u/0/communities/100694529006737757231"><span class="social-icon icon-googleplus"></span><span class="count"></span></a></li>
			</ul>
		
			<br />
			<p class="copy">All content &copy; 2013 <a href="http://www.joed.tk/">JoedSoft</a></p>

		</div>
		<div class="span4">
			<h4>Ofertas Especiales<span class="line"></span></h4>
			<p><b>GRATIS</b> Internet, <b>GRATIS</b> Cochera
			<p>Permancece 5 noches y la sexta es <b>GRATIS</b>!</p>
			<p>Ahorra el <b>20%</b>, somos la mejor opción.</p>
		</div>
		<div class="span4">
			<h4>Tarjetas<span class="line"></span></h4>
			    <ul class="thumbnails">
					<li class="span2">
						<div class="thumbnail">
							<img src="{{ STATIC_URL }}css/images/CreditCards/visa.jpg" alt="" />
						</div>
					</li>				
					<li class="span2">
						<div class="thumbnail">
							<img src="{{ STATIC_URL }}css/images/CreditCards/masterCard.jpg" alt="" />
						</div>
					</li>				
					<li class="span2">
						<div class="thumbnail">
							<img src="{{ STATIC_URL }}css/images/CreditCards/americanExpress.jpg" alt="" />
						</div>
					</li>										
					<li class="span2">
						<div class="thumbnail">
							<img src="{{ STATIC_URL }}css/images/CreditCards/dinersClub.jpg" alt="" />
						</div>
					</li>
					

				</ul>
		</div>
		</div>
		
		</div>
	</footer>

	<!-- // <script src="http://maps.google.com/maps/api/js?sensor=false"></script> -->
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.nivo.slider.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/socialcount.min.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.quicksand.js" type="text/javascript"></script>	
	<script type="text/javascript" src="{{ STATIC_URL }}js/global.js"></script>
	
	<script src="{{ STATIC_URL }}Gallery-master/js/blueimp-gallery.min.js"></script>
	<script>
	document.getElementById('links').onclick = function (event) {
	    event = event || window.event;
	    var target = event.target || event.srcElement,
	        link = target.src ? target.parentNode : target,
	        options = {index: link, event: event},
	        links = this.getElementsByTagName('a');
	    blueimp.Gallery(links, options);
	};
	</script>

</body>
</html>	

wsgi/openshift/templates/HostalRafael/contact.html
{% extends "base.html" %}
{% block title %}Hostal Rafael - {{ myPlace }} {% endblock %}

{% block mapAndText %}
	<div class="span12">	
		<br /><br /><h1>Map and local attractions</h1><br />
	</div>
 <div class="span3 sidebar">
  <ul class="nav">
    <li><a class="active" href="map.html"><span>Area</span> Overview</a></li>
    <li><a href="general.html"><span>Popular</span> attractions</a></li>
    <li><a href="general.html"><span>services</span> and facilities</a></li>
    <li><a href="general.html"><span>nearby</span> shops</a></li>
    <li><a href="general.html"><span>food &amp;</span> drink</a></li>
    <li><a href="typography.html"><span>How to </span>get here</a></li>
  </ul>	
  
</div>

<div class="span8">	
  <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae hendrerit odio. Nam sit amet mi pretium nulla cursus euismod. Pellentesque non nisl quis erat blandit egestas. Fusce tincidunt feugiat posuere. Quisque auctor gravida tortor a hendrerit. Sed id justo urna, sit amet pretium eros. Duis eleifend, urna eget pulvinar laoreet, lacus turpis convallis massa, eget pharetra ante urna accumsan nisl. Ut nec tortor ante, sed dictum urna. In cursus orci sit amet ligula scelerisque vitae iaculis lacus tempus. Nunc pretium tortor vestibulum diam consectetur blandit. Duis at bibendum elit. Donec luctus sem vel erat aliquet tincidunt. </p>

  <div id="map-canvas"></div>


  <div class="row">
   <div class="span4">
    <h3>
      Arts &amp; Culture
    </h3>
    <ul>
      <li>Colosseum/Il Colosseo <small>6.4 km/4.0 miles</small>
      </li>
      <li>Navona Square/Piazza Navona 6.4 km/4.0 miles
      </li>
      <li>Trevi Fountain/Fontana di Trevi 6.4 km/4.0 miles
      </li>
      <li>Capitoline Museums 6.4 km/4.0 miles
      </li>
      <li>Pantheon 6.4 km/4.0 miles
      </li>
      <li>Etruscan Museum 8.0 km/5.0 miles
      </li>
      <li>Gallery of Modern Art 8.0 km/5.0 miles
      </li>
      <li>Spanish Steps/Piazza di Spagna 8.0 km/5.0 miles
      </li>
      <li>Galleria Borghese Museum 8.0 km/5.0 miles
      </li>
      <li>Castel Saint Angelo (Hadrian's Mausoleum) 8.0 km/5.0 miles
      </li>
      <li>Palazzo Al Temps Museum 8.1 km/5.0 miles
      </li>
      <li>Palazzo Massimo Museum 8.1 km/5.0 miles
      </li>
      <li>Vatican Museums 8.1 km/5.0 miles
      </li>
      <li>Tivoli (Roman Villas) 51.0 km/31.7 miles
      </li>
    </ul>
  </div>
  <div class="span4">
    
    <h3>
      Golf
    </h3>
    <ul>
      <li>Golf Club Parco De' Medici 3.2 km/2.0 miles
      </li>
    </ul>
    <h3>
      Government Offices
    </h3>
    <ul>
      <li>French Embassy 6.0 km/3.7 miles
      </li>
      <li>Embassy of the United States of America 8.0 km/5.0 miles
      </li>
      <li>British Embassy 8.0 km/5.0 miles
      </li>
      <li>Japanese Embassy 8.0 km/5.0 miles
      </li>
      <li>Australian Embassy 10.0 km/6.2 miles
      </li>
      <li>Canadian Embassy 10.0 km/6.2 miles
      </li>
      <li>German Embassy 12.0 km/7.5 miles
      </li>
    </ul>
    <h3>
      Local Attractions
    </h3>
    <ul>
      <li>Trastevere 4.8 km/3.0 miles
      </li>
      <li>Sistine Chapel 6.4 km/4.0 miles
      </li>
      <li>Civita Vecchia 71.0 km/44.1 miles
      </li>
    </ul>
  </div>

</div>
<br /><br />




</div>


{% endblock %}

wsgi/openshift/templates/HostalRafael/index.html
{% extends "base.html" %}
{% block title %}Hostal Rafael - {{ myPlace }} {% endblock %}

{% block slider %}
	<div class="row-fluid slideshow-row">
			
		<div class="span12 slideshow">
			<div class="slider-wrapper theme-default">
				<div class="ribbon"></div>
				<div id="nivoslider-125" class="nivoSlider">									
					<!-- <img src="{{ STATIC_URL }}css/images/portadaEdited.png" alt="" /> -->
					<img src="{{ STATIC_URL }}css/images/portadaEdited2.png" alt="" />
					<!-- <img src="{{ STATIC_URL }}css/images/portadaEdited3.png" alt="" /> -->
					

					<!-- <img src="{{ STATIC_URL }}css/images/portadaRafelEdited2.png" alt="" /> -->
					<img src="{{ STATIC_URL }}css/images/portadaRafelEdited2.2.png" alt="" />
					<!-- <img src="{{ STATIC_URL }}css/images/portadaEdited-R1.png" alt="" /> -->
					
					<img src="{{ STATIC_URL }}css/images/playasCamana2edited.png" alt="" />
					<img src="{{ STATIC_URL }}css/images/RioMarOcoñaEdited1.png" alt="" />
				</div>
			</div>
			<!-- <div id="nivoslider-125-caption-0" class="nivo-html-caption">You can add captions too&#8230;</div> -->
		</div>
			
	</div>
{% endblock %}

{% block structureFirst %}
	
	<div class="row-fluid home">
		<div class="span12">
			<h1>Bienvenido a <span>Camaná</span><br>
			<small><span>Hospedaje Rafael</span> lo recibirá con lo mejor de la ciudad</small></h1>
		</div>
	</div>	
	<hr />
	<div class="row-fluid">
		
		<div class="span3">
			<h3><span>H</span>abitaciones</h3>
			<a href="{% url 'toShow:rooms' %}"><img src="{{ STATIC_URL }}css/images/rooms.jpg" alt="" /></a>
			<p>Míra nuestros tipos de habitaciones</p>
		</div>		
		<div class="span3">
			<h3><span>S</span>ervicios</h3>
			<a href="{% url 'toShow:services' %}"><img src="{{ STATIC_URL }}css/images/services.jpg" alt="" /></a>
			<p>Contamos con cochera, WiFi, 
				TV-cable, y mucho mas</p>
		</div>		
		<div class="span3">
			<h3><span>T</span>urismo</h3>
			<a href="{% url 'toShow:tourism' %}"><img src="{{ STATIC_URL }}css/images/tourism.jpg" alt="" /></a>
			<p>Dále una mirada a el atractivo turistico - <b>Camaná</b></p>
		</div>		
		<div class="span3">
			<h3><span>U</span>bicación</h3>
			<a href="{% url 'toShow:contact' %}"><img src="{{ STATIC_URL }}css/images/location.jpg" alt="" /></a>
			<p>Estamos ubicados en un lugar accesible, centro de la ciudad.</p>
		</div>		

	</div>	
{% endblock %}

{% block goodReferences %} 
	<div class="row">
		<div class="span12 what_people_say">
			<div id="quotes">
				<blockquote class="textItem" style="display: none;">
					<p>Este es el mejor hotel donde aya estado.</p>
					<small>Hermanos Villacorta<cite title="Source Title"> - Orquesta</cite></small>
				</blockquote>			
				
				<blockquote class="textItem" style="display: none;">
					<p>El trato es increíble.</p>
					<small>Angelo Gonzales <cite title="Source Title"> - Cliente</cite></small>
				</blockquote>			
				
				<blockquote class="textItem" style="display: none;">
					<p>Cumplío todas mis espectativas</p>
					<small>Agua Bella<cite title="Source Title"> - Agrupación</cite></small>
				</blockquote>
			</div>
		</div>	
	</div>
{% endblock %}

wsgi/openshift/templates/HostalRafael/services.html
{% extends "base.html" %}
{% block title %}Hostal Rafael - {{ myPlace }} {% endblock %}

{% block places %}
	<div class="row">
		
		<div class="span12">	
			<br /><br />
			<h1>Servicios y facilidades</h1>

			<div class="row">
				
				<div class="span6">
					<h3><span>Cochera</span> 24h</h3>
					<a href=""><img src="{{ STATIC_URL }}css/images/services/cochera.jpg" alt="" /></a>
					<p> Cochera las 24h del día. En nuestros dos locales, Rafael I y II </p>
				</div>		
				
				<div class="span6">
					<h3><span>Internet </span> Wi-fi</h3>
					<a href=""><img src="{{ STATIC_URL }}css/images/services/internet.jpg" alt="" /></a>
					<p> Internet/Wi-fi en todos los ambientes del Hotel Rafael I </p>
				</div>				
				
				<div class="span6">
					<h3><span>Sala</span> Descanzo</h3>
					<a href=""><img src="{{ STATIC_URL }}css/images/services/salaDescanzo.jpg" alt="" /></a>
					<p> Sala de descanzo para que pueda disfrutar de las mejores conversaciones en nuestras
					 	instalaciones. </p>
				</div>		
				
				<div class="span6">
					<h3><span>Habitaciones</span> </h3>
					<a href="{% url 'toShow:rooms' %}"><img src="{{ STATIC_URL }}css/images/services/habitaciones.jpg" alt="" /></a>
					<p> Tenemos diferentes tipos de habitaciones para las diferentes necesidades de ustedes, 
						nuestros usuarios, diversidad para su necesidad. </p>
				</div>												
				
			</div>						
		</div>
	</div>
{% endblock %}

{% block goodReferences %} 
	<div class="row">
		<div class="span12 what_people_say">
			<div id="quotes">
				<blockquote class="textItem" style="display: none;">
					<p>Este es el mejor hotel donde aya estado.</p>
					<small>Hermanos Villacorta<cite title="Source Title"> - Orquesta</cite></small>
				</blockquote>			
				
				<blockquote class="textItem" style="display: none;">
					<p>El trato es increíble.</p>
					<small>Angelo Gonzales <cite title="Source Title"> - Cliente</cite></small>
				</blockquote>			
				
				<blockquote class="textItem" style="display: none;">
					<p>Cumplío todas mis espectativas</p>
					<small>Agua Bella<cite title="Source Title"> - Agrupación</cite></small>
				</blockquote>
			</div>
		</div>	
	</div>
{% endblock %}

wsgi/openshift/templates/home/home.html
<b>
Yeah Django!
<b>
<br />
let's <a href="/admin">admin </a>